# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workgen', '0002_auto_20180525_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movements',
            old_name='movements',
            new_name='musclegroup',
        ),
    ]
