# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workgen', '0006_auto_20180528_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts',
            name='name',
        ),
    ]
