# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-01 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgen', '0007_remove_workouts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='repsperset',
            field=models.IntegerField(default=10),
        ),
    ]
