# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-01 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgen', '0008_movements_repsperset'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='wtype',
            field=models.CharField(default='Barbell', max_length=255),
        ),
    ]
