# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-02 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workgen', '0010_workouts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouts',
            old_name='WorkoutDate',
            new_name='workoutdate',
        ),
    ]
