# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-08 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgen', '0011_auto_20180601_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='Equipment',
            field=models.ManyToManyField(related_name='users', to='workgen.Equipment'),
        ),
    ]
