# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-08 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workgen', '0012_auto_20180608_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Equipment',
            new_name='equipment',
        ),
    ]
