# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-09 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgen', '0013_auto_20180608_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
